import { Employee } from './types';

export const mockEmployees: Employee[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1 (555) 123-4567',
    department: 'Engineering',
    role: 'Senior Developer',
    status: 'Active',
    location: 'New York',
    joinDate: '2020-01-15',
    avatarUrl: 'https://i.pravatar.cc/150?u=1',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phone: '+1 (555) 234-5678',
    department: 'Design',
    role: 'UI/UX Designer',
    status: 'Active',
    location: 'San Francisco',
    joinDate: '2019-11-01',
    avatarUrl: 'https://i.pravatar.cc/150?u=2',
  },
  {
    id: 3,
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.j@example.com',
    phone: '+1 (555) 345-6789',
    department: 'Product',
    role: 'Product Manager',
    status: 'On Leave',
    location: 'Chicago',
    joinDate: '2021-03-10',
    avatarUrl: 'https://i.pravatar.cc/150?u=3',
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.d@example.com',
    phone: '+1 (555) 456-7890',
    department: 'Marketing',
    role: 'Marketing Specialist',
    status: 'Active',
    location: 'London',
    joinDate: '2022-06-20',
    avatarUrl: 'https://i.pravatar.cc/150?u=4',
  },
  {
    id: 5,
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.b@example.com',
    phone: '+1 (555) 567-8901',
    department: 'Engineering',
    role: 'DevOps Engineer',
    status: 'Inactive',
    location: 'Remote',
    joinDate: '2018-08-15',
    avatarUrl: 'https://i.pravatar.cc/150?u=5',
  },
  {
    id: 6,
    firstName: 'Sarah',
    lastName: 'Wilson',
    email: 'sarah.w@example.com',
    phone: '+1 (555) 678-9012',
    department: 'HR',
    role: 'HR Manager',
    status: 'Active',
    location: 'New York',
    joinDate: '2017-05-01',
    avatarUrl: 'https://i.pravatar.cc/150?u=6',
  },
  {
    id: 7,
    firstName: 'David',
    lastName: 'Taylor',
    email: 'david.t@example.com',
    phone: '+1 (555) 789-0123',
    department: 'Sales',
    role: 'Sales Executive',
    status: 'Active',
    location: 'Austin',
    joinDate: '2023-01-10',
    avatarUrl: 'https://i.pravatar.cc/150?u=7',
  },
  {
    id: 8,
    firstName: 'Jessica',
    lastName: 'Martinez',
    email: 'jessica.m@example.com',
    phone: '+1 (555) 890-1234',
    department: 'Support',
    role: 'Support Lead',
    status: 'Active',
    location: 'Miami',
    joinDate: '2020-09-15',
    avatarUrl: 'https://i.pravatar.cc/150?u=8',
  },
  {
    id: 9,
    firstName: 'Christopher',
    lastName: 'Anderson',
    email: 'chris.a@example.com',
    phone: '+1 (555) 901-2345',
    department: 'Engineering',
    role: 'Frontend Developer',
    status: 'Active',
    location: 'Seattle',
    joinDate: '2021-11-20',
    avatarUrl: 'https://i.pravatar.cc/150?u=9',
  },
  {
    id: 10,
    firstName: 'Amanda',
    lastName: 'Thomas',
    email: 'amanda.t@example.com',
    phone: '+1 (555) 012-3456',
    department: 'Finance',
    role: 'Accountant',
    status: 'On Leave',
    location: 'Boston',
    joinDate: '2019-02-28',
    avatarUrl: 'https://i.pravatar.cc/150?u=10',
  },
  {
    id: 11,
    firstName: 'Matthew',
    lastName: 'Hernandez',
    email: 'matthew.h@example.com',
    phone: '+1 (555) 123-4567',
    department: 'Engineering',
    role: 'QA Engineer',
    status: 'Active',
    location: 'Denver',
    joinDate: '2022-04-15',
    avatarUrl: 'https://i.pravatar.cc/150?u=11',
  },
  {
    id: 12,
    firstName: 'Olivia',
    lastName: 'Moore',
    email: 'olivia.m@example.com',
    phone: '+1 (555) 234-5678',
    department: 'Design',
    role: 'Graphic Designer',
    status: 'Inactive',
    location: 'Portland',
    joinDate: '2020-07-01',
    avatarUrl: 'https://i.pravatar.cc/150?u=12',
  },
];
